### ISSUE TITLE
Feature Request: support multiple AAB files via BITRISE_AAB_PATH_LIST

### ISSUE THREAD

**Issue by EyMaddis** [bitrise-steplib/bitrise-step-export-universal-apk#13]
When building multiple variants, we could use this to also generate multiple apk files since the sign step does support it:
https://devcenter.bitrise.io/deploy/android-deploy/generate-and-deploy-multiple-flavor-apks-in-a-single-workflow/

**Comment by shreyanshp** [comment]
@EyMaddis Just curious to know if you found any workaround for this?

**Comment by androideveloper** [comment]
@shreyanshp you can have multiple of these steps in the single workflow and generate as many apks as you want

**Comment by shreyanshp** [comment]
@androideveloper hey buddy, thanks for your reply
However I am still not sure how to use multiple of these steps as the input remains just which is `$BITRISE_SIGNED_AAB_PATH_LIST` (the output of Android Sign step), let me know if you have any info, much appreciated !

**Comment by androideveloper** [comment]
What do you mean with input?
You can change the input params and export universal apk from the any aab that was generated. In our case it looks like this:
```
    - bitrise-step-export-universal-apk@0:
        inputs:
          - keystore_url: "$BITRISEIO_ANDROID_KEYSTORE_URL"
          - keystore_password: "$BITRISEIO_ANDROID_KEYSTORE_PASSWORD"
          - keystore_alias: "$BITRISEIO_ANDROID_KEYSTORE_ALIAS"
          - private_key_password: "$BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD"
          - aab_path: "$BITRISE_DEPLOY_DIR/xxx.aab"
        title: Export xxx Universal APK
    - bitrise-step-export-universal-apk@0:
        inputs:
          - keystore_url: "$BITRISEIO_ANDROID_KEYSTORE_URL"
          - keystore_password: "$BITRISEIO_ANDROID_KEYSTORE_PASSWORD"
          - keystore_alias: "$BITRISEIO_ANDROID_KEYSTORE_ALIAS"
          - private_key_password: "$BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD"
          - aab_path: "$BITRISE_DEPLOY_DIR/yyy.aab"
        title: Export yyy Universal APK
```
